baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Site"
theme = "bloggeri"

[[menu.main]]
    name = "About"
    url = "/about"

[[menu.main]]
    name = "Blog"
    url = "/blog"

[[menu.social]]
    name = "GitHub"
    url = "https://github.com/pakstech"
    pre = "<i class='fab fa-github'></i>"

[[menu.social]]
    name = "YouTube"
    url = "https://www.youtube.com/channel/UCg_e3UBPs-BxPo_jVg1gGOQ"
    pre = "<i class='fab fa-youtube'></i>"

[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/pakstech"
    pre = "<i class='fab fa-twitter'></i>"

[params]
    description = "My site description"